[package]
name = "coap-lite"
description = """
A lightweight CoAP message manipulation crate, ideal for embedded environments.
"""
version = "0.4.1"
authors = ["Martin Disch <martindisch@gmail.com>"]
repository = "https://github.com/martindisch/coap-lite"
readme = "README.md"
keywords = ["coap"]
categories = ["network-programming", "no-std", "embedded"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
coap-message = { version = "0.1.1", optional = true }

# actually they are dev-dependencies, but those can't be optional
coap-handler = { version = "0.0.2", optional = true }
serde = { version = "1.0.123", default-features = false, features = ["alloc"], optional = true }
coap-numbers = { version = "^0.1", optional = true }

[dev-dependencies]
chrono = "*"
rustls = "0.19.1"
env_logger = "0.8.2"
log = "0.4.4"
webpki = "0.21.0"
webpki-roots = "0.21"
criterion = "0.3.0"
rustls-pemfile = "0.2.1"
rand = "0.8.0"
serde_json = "1"

[features]
default = ["std"]
std = []
with-coap-message = ["coap-message"]

example-server_coaphandler = ["with-coap-message", "coap-handler", "serde", "coap-numbers"]

[badges]
maintenance = { status = "passively-maintained" }

[[example]]
name = "server_coaphandler"
required-features = ["example-server_coaphandler"]

[[example]]
name = "server_tcp"
